import type {
  Capability,
  CanvasKind,
  ScenarioAction,
  ScenarioDefinition,
  ScenarioGroup,
  ScenarioRole,
} from './scenario';

const action = (
  id: string,
  label: string,
  nextStatus: string,
  eventText: string,
  capabilities: Capability[],
  tone: ScenarioAction['tone'] = 'default',
): ScenarioAction => ({ id, label, nextStatus, eventText, capabilities, tone });

const roles = (...entries: [string, string][]): ScenarioRole[] =>
  entries.map(([id, label]) => ({ id, label }));

const scenario = (
  groupId: string,
  id: string,
  title: string,
  summary: string,
  canvas: CanvasKind,
  sceneRoles: ScenarioRole[],
  initialStatus: string,
  actions: ScenarioAction[],
  supportsRealRtm = false,
): ScenarioDefinition => ({
  groupId,
  id,
  title,
  summary,
  canvas,
  roles: sceneRoles,
  initialStatus,
  actions,
  supportsRealRtm,
});

export const scenarioGroups: ScenarioGroup[] = [
  {
    id: 'social',
    label: '社交 / 娱乐',
    shortLabel: '社交',
    scenarios: [
      scenario(
        'social',
        'social-presence',
        '在线、好友与忙闲状态',
        '让好友、主播和关注者实时看到可信的在线与忙闲变化。',
        'chat',
        roles(['self', '我的账号'], ['friend', '好友视角']),
        '离线',
        [
          action('go-online', '上线', '在线', '账号已上线并广播在线状态', ['Presence']),
          action('set-busy', '设为忙碌', '忙碌', '忙闲状态已同步给好友', ['Presence', 'Storage']),
          action('watch-online', '关注上线', '已关注', '已订阅好友上线通知', ['Presence', '用户消息']),
        ],
      ),
      scenario(
        'social',
        'social-chat',
        '私聊、群聊与消息回执',
        '用统一的消息链路完成私聊、群聊和轻量回执。',
        'chat',
        roles(['sender', '发送者'], ['receiver', '接收者']),
        '会话就绪',
        [
          action('send-direct', '发送私信', '消息已送达', '私信已定向发送', ['用户消息']),
          action('send-group', '发送群消息', '群消息已发送', '消息已广播到群组频道', ['消息频道']),
          action('mark-read', '标记已读', '已读', '已读回执已返回发送者', ['用户消息']),
        ],
      ),
      scenario(
        'social',
        'voice-room-interaction',
        '礼物、弹幕与房内互动',
        '把弹幕、礼物与表情作为低延迟房间事件驱动互动氛围。',
        'room',
        roles(['host', '房主'], ['audience', '听众']),
        '房间进行中',
        [
          action('send-barrage', '发送弹幕', '弹幕已上屏', '弹幕已广播到房间', ['消息频道']),
          action('send-gift', '赠送礼物', '礼物已展示', '礼物事件已广播并更新榜单', ['消息频道', 'Storage']),
          action('send-emoji', '发送表情', '表情已展示', '表情互动已发送', ['消息频道']),
        ],
      ),
      scenario(
        'social',
        'voice-room-seats',
        '上下麦与麦位状态',
        '通过请求、审批、共享快照和麦位锁保持所有人的麦位一致。',
        'room',
        roles(['host', '房主'], ['audience', '听众']),
        '围观中',
        [
          action('raise-hand', '举手申请', '申请中', '听众已提交上麦申请', ['消息频道']),
          action('approve-seat', '同意上麦', '1 号麦位已占用', '房主同意申请并写入麦位快照', ['消息频道', 'Storage', 'Lock']),
          action('reject-seat', '拒绝申请', '围观中', '房主已拒绝上麦申请', ['消息频道']),
          action('mute-seat', '禁麦', '1 号麦位已禁麦', '麦位发言权已被收回', ['消息频道', 'Storage']),
          action('leave-seat', '下麦', '围观中', '麦位已释放并同步给房间成员', ['消息频道', 'Storage', 'Lock']),
        ],
        true,
      ),
      scenario(
        'social',
        'live-social-pk',
        '连麦、PK 与房间互动',
        '同步主播邀请、PK 回合、比分和结束状态。',
        'room',
        roles(['anchor-a', '主播 A'], ['anchor-b', '主播 B']),
        '单人直播中',
        [
          action('start-pk', '发起 PK', '等待应战', '主播 A 已发出 PK 邀请', ['用户消息']),
          action('accept-pk', '接受 PK', 'PK 进行中', '双方房间已进入同一 PK 回合', ['用户消息', '消息频道']),
          action('score-pk', '增加比分', 'A 队领先', '礼物计分事件已同步', ['消息频道', 'Storage']),
          action('end-pk', '结束回合', 'PK 已结束', '最终比分已锁定并广播', ['消息频道', 'Storage']),
        ],
      ),
      scenario(
        'social',
        'one-to-one-call',
        '呼叫、接听与挂断',
        '在媒体建立前后同步邀请、振铃和通话生命周期。',
        'call',
        roles(['caller', '呼叫方'], ['callee', '接听方']),
        '空闲',
        [
          action('call', '发起呼叫', '振铃中', '呼叫邀请已送达对方', ['用户消息']),
          action('accept-call', '接听', '通话中', '接听结果已返回呼叫方', ['用户消息']),
          action('reject-call', '拒接', '已拒接', '拒接结果已同步', ['用户消息']),
          action('hang-up', '挂断', '已结束', '挂断事件已同步到双方', ['用户消息'], 'danger'),
        ],
      ),
      scenario(
        'social',
        'room-moderation',
        '禁言、踢人、举报与封禁',
        '让管理动作实时生效，并用共享状态保持治理结果一致。',
        'room',
        roles(['moderator', '管理员'], ['member', '房间成员']),
        '房间正常',
        [
          action('mute-member', '禁言成员', '成员已禁言', '禁言指令已广播', ['消息频道', 'Storage']),
          action('report-member', '提交举报', '举报审核中', '举报事件已提交审核链路', ['用户消息']),
          action('remove-member', '踢出房间', '成员已移出', '踢出指令已生效', ['消息频道', 'Storage'], 'danger'),
          action('restore-member', '解除限制', '房间正常', '成员权限已恢复', ['消息频道', 'Storage']),
        ],
      ),
    ],
  },
  {
    id: 'education',
    label: '在线教育',
    shortLabel: '教育',
    scenarios: [
      scenario(
        'education',
        'classroom-messaging',
        '课堂 IM 与班级通知',
        '把课堂提问、助教答疑和班级通知放在同一实时链路中。',
        'classroom',
        roles(['teacher', '老师'], ['student', '学生'], ['assistant', '助教']),
        '上课中',
        [
          action('ask-question', '提交问题', '等待答疑', '学生问题已发送到课堂', ['消息频道']),
          action('answer-question', '助教答疑', '问题已解答', '答疑消息已同步给学生', ['用户消息', '消息频道']),
          action('class-notice', '发布通知', '通知已发布', '班级通知已广播', ['消息频道']),
        ],
      ),
      scenario(
        'education',
        'classroom-stage',
        '举手、上下麦与连麦',
        '用实时审批和发言权状态完成课堂会控。',
        'classroom',
        roles(['teacher', '老师'], ['student', '学生']),
        '听课中',
        [
          action('raise-hand', '举手', '已举手', '学生已提交发言申请', ['消息频道']),
          action('call-student', '点名上台', '发言中', '老师已授予发言权', ['消息频道', 'Storage']),
          action('mute-student', '暂停发言', '已静音', '老师已暂停学生发言', ['消息频道', 'Storage']),
          action('seat-student', '结束发言', '已落座', '发言权已收回', ['消息频道', 'Storage']),
        ],
      ),
      scenario(
        'education',
        'classroom-quiz',
        '答题、抢答、投票与签到',
        '实时下发互动任务并快速汇总结果。',
        'classroom',
        roles(['teacher', '老师'], ['student', '学生']),
        '互动待开始',
        [
          action('publish-quiz', '发布题目', '答题中', '题目已广播到全班', ['消息频道']),
          action('buzz-in', '抢答', '抢答成功', '首个有效抢答已锁定', ['消息频道', 'Lock']),
          action('submit-vote', '提交投票', '投票已提交', '投票结果已实时汇总', ['消息频道', 'Storage']),
          action('check-in', '签到', '签到成功', '签到状态已同步', ['用户消息', 'Storage']),
        ],
      ),
      scenario(
        'education',
        'education-device',
        '设备在线与远程指令',
        '同步学习终端在线状态并安全地下发管理指令。',
        'device',
        roles(['admin', '管理员'], ['terminal', '学习终端']),
        '设备离线',
        [
          action('device-online', '设备上线', '设备在线', '学习终端已上线', ['Presence']),
          action('bind-device', '绑定设备', '已绑定', '终端绑定关系已确认', ['用户消息', 'Storage']),
          action('push-policy', '下发策略', '策略已应用', '课堂策略已下发并执行', ['用户消息']),
        ],
      ),
    ],
  },
  {
    id: 'enterprise',
    label: '企业服务 / 垂直行业',
    shortLabel: '企业',
    scenarios: [
      scenario(
        'enterprise',
        'enterprise-collaboration',
        '单聊、群聊与组织消息',
        '承载协作消息、组织通知和文件流转状态。',
        'chat',
        roles(['employee', '员工'], ['manager', '管理员']),
        '协作在线',
        [
          action('send-chat', '发送单聊', '单聊已送达', '协作消息已送达同事', ['用户消息']),
          action('org-notice', '发布组织通知', '通知已发布', '组织通知已广播', ['消息频道']),
          action('file-status', '更新文件状态', '文件已接收', '文件传输状态已同步', ['用户消息', 'Storage']),
        ],
      ),
      scenario(
        'enterprise',
        'field-operations',
        '设备状态、告警与调度',
        '把现场告警、人员状态和任务调度连接成处置闭环。',
        'operations',
        roles(['dispatcher', '调度员'], ['engineer', '现场工程师']),
        '现场正常',
        [
          action('raise-alert', '上报告警', '告警中', '设备异常已上报', ['消息频道']),
          action('assign-task', '指派任务', '处理中', '处置任务已定向发送', ['用户消息', 'Storage']),
          action('resolve-task', '确认处理', '已恢复', '处理结果已回传并关闭告警', ['用户消息', 'Storage']),
        ],
      ),
      scenario(
        'enterprise',
        'video-meeting',
        '入会、举手、共享与会控',
        '在音视频之外同步邀请、成员、共享和会议控制状态。',
        'meeting',
        roles(['host', '主持人'], ['attendee', '参会者']),
        '待入会',
        [
          action('invite-attendee', '发送邀请', '邀请已发送', '入会邀请已送达', ['用户消息']),
          action('join-meeting', '加入会议', '会议中', '参会成员状态已同步', ['Presence', '消息频道']),
          action('raise-hand', '举手', '已举手', '举手事件已通知主持人', ['消息频道']),
          action('share-screen', '开始共享', '共享中', '共享状态已广播', ['消息频道', 'Storage']),
          action('end-meeting', '结束会议', '已结束', '会议结束指令已广播', ['消息频道'], 'danger'),
        ],
      ),
    ],
  },
  {
    id: 'iot',
    label: 'IoT / 智能硬件',
    shortLabel: 'IoT',
    scenarios: [
      scenario(
        'iot',
        'device-telemetry',
        '在线状态与遥测上报',
        '持续同步设备在线、电量、温度和位置等轻量状态。',
        'device',
        roles(['operator', '设备管理员'], ['device', '智能设备']),
        '设备离线',
        [
          action('go-online', '设备上线', '设备在线', '设备连接状态已同步', ['Presence']),
          action('report-battery', '上报电量', '电量 82%', '最新电量已上报', ['消息频道', 'Storage']),
          action('report-telemetry', '上报温度与位置', '遥测已更新', '温度和位置数据已刷新', ['消息频道', 'Storage']),
        ],
      ),
      scenario(
        'iot',
        'device-control',
        '远程指令、任务与配置下发',
        '用定向命令和双阶段 ACK 建立设备控制闭环。',
        'device',
        roles(['controller', '控制端'], ['device', '设备端']),
        '设备待机',
        [
          action('power-on', '开启设备', '设备运行中', '开机指令已执行并回传 ACK', ['用户消息', 'Presence']),
          action('move-device', '向右移动', '移动完成', '移动指令已执行并回传位置', ['用户消息']),
          action('push-config', '下发配置', '配置已应用', '配置版本已更新', ['用户消息', 'Storage']),
          action('stop-device', '紧急停止', '设备已停止', '停止指令已优先执行', ['用户消息'], 'danger'),
        ],
        true,
      ),
      scenario(
        'iot',
        'security-alerts',
        '告警事件实时推送',
        '把传感告警实时分发给多个处置端并同步处理结果。',
        'operations',
        roles(['sensor', '传感器'], ['responder', '处置人员']),
        '监控正常',
        [
          action('trigger-alert', '触发告警', '告警中', '异常事件已推送到处置端', ['消息频道']),
          action('ack-alert', '确认告警', '处理中', '处置人员已确认接单', ['用户消息', 'Storage']),
          action('resolve-alert', '完成处置', '已恢复', '告警已关闭并同步多端', ['消息频道', 'Storage']),
        ],
      ),
    ],
  },
  {
    id: 'content',
    label: '内容 / 直播',
    shortLabel: '直播',
    scenarios: [
      scenario(
        'content',
        'live-chat-gifts',
        '弹幕、公屏与礼物',
        '对高频弹幕、点赞和礼物事件采用适合的广播策略。',
        'room',
        roles(['anchor', '主播'], ['viewer', '观众']),
        '直播中',
        [
          action('send-comment', '发送弹幕', '弹幕已上屏', '弹幕已广播', ['消息频道']),
          action('send-like', '点赞', '点赞已聚合', '点赞事件已合并广播', ['消息频道']),
          action('send-gift', '送出礼物', '礼物已展示', '礼物事件与榜单已同步', ['消息频道', 'Storage']),
        ],
      ),
      scenario(
        'content',
        'live-operations',
        '开播、进出房与主播状态',
        '同步开关播、观众进出和主播忙闲状态。',
        'room',
        roles(['anchor', '主播'], ['viewer', '观众']),
        '未开播',
        [
          action('start-live', '开始直播', '直播中', '开播状态已广播', ['消息频道', 'Storage']),
          action('viewer-join', '观众进房', '观众 128 人', '成员与房间人数已更新', ['Presence', 'Storage']),
          action('set-busy', '主播忙碌', '主播忙碌', '主播忙闲状态已同步', ['Presence', 'Storage']),
          action('stop-live', '结束直播', '已关播', '关播状态已广播', ['消息频道', 'Storage'], 'danger'),
        ],
      ),
      scenario(
        'content',
        'live-guests',
        '连麦、上下麦与嘉宾控制',
        '同步嘉宾邀请、席位和发言权变化。',
        'room',
        roles(['host', '主持人'], ['guest', '嘉宾']),
        '等待嘉宾',
        [
          action('invite-guest', '邀请嘉宾', '邀请中', '嘉宾邀请已送达', ['用户消息']),
          action('accept-invite', '接受邀请', '嘉宾已上麦', '嘉宾席位已同步', ['用户消息', 'Storage', 'Lock']),
          action('mute-guest', '收回发言权', '嘉宾已静音', '嘉宾发言权已更新', ['消息频道', 'Storage']),
          action('remove-guest', '嘉宾下麦', '等待嘉宾', '嘉宾席位已释放', ['消息频道', 'Storage', 'Lock']),
        ],
      ),
    ],
  },
  {
    id: 'healthcare',
    label: '医疗健康',
    shortLabel: '医疗',
    scenarios: [
      scenario(
        'healthcare',
        'telemedicine-call',
        '在线问诊呼叫与通话状态',
        '在医患会话中同步邀请、振铃、接听和结束状态。',
        'call',
        roles(['doctor', '医生'], ['patient', '患者']),
        '等待问诊',
        [
          action('start-consult', '发起问诊', '患者振铃中', '问诊邀请已安全送达', ['用户消息']),
          action('accept-consult', '接听问诊', '问诊中', '接听状态已同步双方', ['用户消息']),
          action('end-consult', '结束问诊', '问诊已结束', '会话结束状态已同步', ['用户消息'], 'danger'),
        ],
      ),
    ],
  },
  {
    id: 'mobility',
    label: '出行 / 本地生活',
    shortLabel: '出行',
    scenarios: [
      scenario(
        'mobility',
        'dispatch-order',
        '派单与订单状态',
        '实时下发调度任务并同步履约阶段。',
        'order',
        roles(['dispatcher', '调度员'], ['driver', '司机'], ['customer', '乘客']),
        '待派单',
        [
          action('dispatch', '派单', '待接单', '新订单已推送给附近司机', ['用户消息']),
          action('accept-order', '接单', '服务中', '司机已接单，订单状态已同步', ['用户消息', 'Storage']),
          action('complete-order', '完成订单', '已完成', '履约结果已同步给调度与乘客', ['消息频道', 'Storage']),
        ],
      ),
      scenario(
        'mobility',
        'driver-rider-messaging',
        '司机、骑手与乘客通信',
        '通过匿名业务身份完成隐私呼叫和订单内消息。',
        'call',
        roles(['driver', '司机 / 骑手'], ['passenger', '乘客']),
        '等待联系',
        [
          action('privacy-call', '发起隐私呼叫', '振铃中', '匿名呼叫邀请已送达', ['用户消息']),
          action('send-order-message', '发送订单消息', '消息已送达', '订单内消息已送达', ['用户消息']),
          action('contact-support', '联系客服', '客服已接入', '客服会话已加入', ['用户消息', '消息频道']),
        ],
      ),
    ],
  },
  {
    id: 'gaming',
    label: '游戏',
    shortLabel: '游戏',
    scenarios: [
      scenario(
        'gaming',
        'gaming-voice-social',
        '游戏语音房与聊天',
        '同步队友在线、房间成员、麦位和轻量聊天。',
        'room',
        roles(['captain', '队长'], ['player', '玩家']),
        '组队大厅',
        [
          action('join-party', '加入队伍', '已入队', '玩家已加入语音房', ['Presence', '消息频道']),
          action('friend-online', '好友上线', '好友在线', '好友上线提醒已送达', ['Presence', '用户消息']),
          action('take-seat', '开启语音', '语音席位已占用', '玩家已占用语音席位', ['消息频道', 'Storage', 'Lock']),
          action('send-team-chat', '发送队伍消息', '消息已发送', '队伍聊天已广播', ['消息频道']),
        ],
      ),
    ],
  },
];

export const allScenarios = scenarioGroups.flatMap((group) => group.scenarios);

export function getScenario(id: string): ScenarioDefinition | undefined {
  return allScenarios.find((item) => item.id === id);
}
